COMPILER_RT_BUILD_FILE = """load("@rules_ll//ll:defs.bzl", "ll_bootstrap_library")

ll_bootstrap_library(
    name = "libll_compiler-rt",
    deps = [
        "//compiler-rt/lib:builtins",
        "//compiler-rt/lib:crt",
    ],
    visibility = ["//visibility:public"],
)"""

COMPILER_RT_LIB_BUILD_FILE = """load("@rules_ll//ll:defs.bzl", "ll_bootstrap_library")

GENERIC_SOURCES = [
    "builtins/absvdi2.c",
    "builtins/absvsi2.c",
    "builtins/absvti2.c",
    "builtins/adddf3.c",
    "builtins/addsf3.c",
    "builtins/addvdi3.c",
    "builtins/addvsi3.c",
    "builtins/addvti3.c",
    "builtins/apple_versioning.c",
    "builtins/ashldi3.c",
    "builtins/ashlti3.c",
    "builtins/ashrdi3.c",
    "builtins/ashrti3.c",
    "builtins/bswapdi2.c",
    "builtins/bswapsi2.c",
    "builtins/clzdi2.c",
    "builtins/clzsi2.c",
    "builtins/clzti2.c",
    "builtins/cmpdi2.c",
    "builtins/cmpti2.c",
    "builtins/comparedf2.c",
    "builtins/comparesf2.c",
    "builtins/ctzdi2.c",
    "builtins/ctzsi2.c",
    "builtins/ctzti2.c",
    "builtins/divdc3.c",
    "builtins/divdf3.c",
    "builtins/divdi3.c",
    "builtins/divmoddi4.c",
    "builtins/divmodsi4.c",
    "builtins/divmodti4.c",
    "builtins/divsc3.c",
    "builtins/divsf3.c",
    "builtins/divsi3.c",
    "builtins/divti3.c",
    "builtins/extendsfdf2.c",
    "builtins/extendhfsf2.c",
    "builtins/ffsdi2.c",
    "builtins/ffssi2.c",
    "builtins/ffsti2.c",
    "builtins/fixdfdi.c",
    "builtins/fixdfsi.c",
    "builtins/fixdfti.c",
    "builtins/fixsfdi.c",
    "builtins/fixsfsi.c",
    "builtins/fixsfti.c",
    "builtins/fixunsdfdi.c",
    "builtins/fixunsdfsi.c",
    "builtins/fixunsdfti.c",
    "builtins/fixunssfdi.c",
    "builtins/fixunssfsi.c",
    "builtins/fixunssfti.c",
    "builtins/floatdidf.c",
    "builtins/floatdisf.c",
    "builtins/floatsidf.c",
    "builtins/floatsisf.c",
    "builtins/floattidf.c",
    "builtins/floattisf.c",
    "builtins/floatundidf.c",
    "builtins/floatundisf.c",
    "builtins/floatunsidf.c",
    "builtins/floatunsisf.c",
    "builtins/floatuntidf.c",
    "builtins/floatuntisf.c",
    "builtins/fp_mode.c",
    "builtins/int_util.c",
    "builtins/lshrdi3.c",
    "builtins/lshrti3.c",
    "builtins/moddi3.c",
    "builtins/modsi3.c",
    "builtins/modti3.c",
    "builtins/muldc3.c",
    "builtins/muldf3.c",
    "builtins/muldi3.c",
    "builtins/mulodi4.c",
    "builtins/mulosi4.c",
    "builtins/muloti4.c",
    "builtins/mulsc3.c",
    "builtins/mulsf3.c",
    "builtins/multi3.c",
    "builtins/mulvdi3.c",
    "builtins/mulvsi3.c",
    "builtins/mulvti3.c",
    "builtins/negdf2.c",
    "builtins/negdi2.c",
    "builtins/negsf2.c",
    "builtins/negti2.c",
    "builtins/negvdi2.c",
    "builtins/negvsi2.c",
    "builtins/negvti2.c",
    "builtins/os_version_check.c",
    "builtins/paritydi2.c",
    "builtins/paritysi2.c",
    "builtins/parityti2.c",
    "builtins/popcountdi2.c",
    "builtins/popcountsi2.c",
    "builtins/popcountti2.c",
    "builtins/powidf2.c",
    "builtins/powisf2.c",
    "builtins/subdf3.c",
    "builtins/subsf3.c",
    "builtins/subvdi3.c",
    "builtins/subvsi3.c",
    "builtins/subvti3.c",
    "builtins/trampoline_setup.c",
    "builtins/truncdfhf2.c",
    "builtins/truncdfsf2.c",
    "builtins/truncsfhf2.c",
    "builtins/ucmpdi2.c",
    "builtins/ucmpti2.c",
    "builtins/udivdi3.c",
    "builtins/udivmoddi4.c",
    "builtins/udivmodsi4.c",
    "builtins/udivmodti4.c",
    "builtins/udivsi3.c",
    "builtins/udivti3.c",
    "builtins/umoddi3.c",
    "builtins/umodsi3.c",
    "builtins/umodti3.c",

    # Not Fuchsia and not a bare-metal build.
    "builtins/emutls.c",
    "builtins/enable_execute_stack.c",
    "builtins/eprintf.c",

    # Not sure whether we want atomic in this or separately.
    "builtins/atomic.c",

    # Not sure whether this is for libunwind or gcc_s. gotta check.
    "builtins/gcc_personality_v0.c",

    # Not Fuchsia.
    "builtins/clear_cache.c",
]

GENERIC_TF_SOURCES = [
    "builtins/addtf3.c",
    "builtins/comparetf2.c",
    "builtins/divtc3.c",
    "builtins/divtf3.c",
    "builtins/extenddftf2.c",
    "builtins/extendhftf2.c",
    "builtins/extendsftf2.c",
    "builtins/fixtfdi.c",
    "builtins/fixtfsi.c",
    "builtins/fixtfti.c",
    "builtins/fixunstfdi.c",
    "builtins/fixunstfsi.c",
    "builtins/fixunstfti.c",
    "builtins/floatditf.c",
    "builtins/floatsitf.c",
    "builtins/floattitf.c",
    "builtins/floatunditf.c",
    "builtins/floatunsitf.c",
    "builtins/floatuntitf.c",
    "builtins/multc3.c",
    "builtins/multf3.c",
    "builtins/powitf2.c",
    "builtins/subtf3.c",
    "builtins/trunctfdf2.c",
    "builtins/trunctfhf2.c",
    "builtins/trunctfsf2.c",
]

X86_ARCH_SOURCES = [
    "builtins/cpu_model.c",
    "builtins/i386/fp_mode.c",  # Used on 64-bit as well.
]

X86_64_SOURCES = GENERIC_SOURCES + GENERIC_TF_SOURCES + X86_ARCH_SOURCES + [
    "builtins/x86_64/floatdidf.c",
    "builtins/x86_64/floatdisf.c",
    "builtins/x86_64/floatundidf.S",
    "builtins/x86_64/floatundisf.S",

    # Only on non-Android.
    "builtins/x86_64/floatdixf.c",
    "builtins/x86_64/floatundixf.S",
]

ll_bootstrap_library(
    name = "builtins",
    srcs = X86_64_SOURCES,
    hdrs = [
        "builtins/int_lib.h",
        "builtins/int_types.h",
        "builtins/int_endianness.h",
        "builtins/fp_lib.h",
        "builtins/int_util.h",
        "builtins/int_math.h",
        "builtins/fp_compare_impl.inc",
        "builtins/fp_mode.h",
        "builtins/fp_add_impl.inc",
        "builtins/int_mulo_impl.inc",
        "builtins/int_div_impl.inc",
        "builtins/fp_fixuint_impl.inc",
        "builtins/fp_extend_impl.inc",
        "builtins/fp_trunc_impl.inc",
        "builtins/fp_mul_impl.inc",
        "builtins/fp_extend.h",
        "builtins/assembly.h",
        "builtins/fp_trunc.h",
        "builtins/int_mulv_impl.inc",
        "builtins/fp_fixint_impl.inc",
        "builtins/fp_div_impl.inc",
    ],
    visibility = ["//visibility:public"],
)

ll_bootstrap_library(
    name = "crt",
    srcs = [
        "crt/crtbegin.c",
        "crt/crtend.c",
    ],
    visibility = ["//visibility:public"],
)
"""
